/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import static EncodePassword.AES.setKey;
import Processes.ClockThread;
import Processes.Staff;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hindu
 */
public class StaffSignUp extends javax.swing.JFrame {

    /**
     * Creates new form Staff_SignUp
     */
    public StaffSignUp() {
        initComponents();
        initClock();
        setResizable(false);
        this.setLocationRelativeTo(null);
        showCbStaffData();
        resetStaffSignUp();
    }

    private void initClock() {
        ClockThread ct = new ClockThread(lbClock, lbTime);
        ct.start();
    }

    private void showCbStaffData() {
        ArrayList<String> data = Staff.getData();
        for (String dt : data) {
            cbExpertise.addItem(dt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        btnGroupGender = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        radBtnManager = new javax.swing.JRadioButton();
        cbExpertise = new javax.swing.JComboBox<>();
        txtExperience = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        radBtnInstructor = new javax.swing.JRadioButton();
        radBtnCashier = new javax.swing.JRadioButton();
        jSeparator13 = new javax.swing.JSeparator();
        txtSalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbClock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dcBirthday = new com.toedter.calendar.JDateChooser();
        dcDateJoin = new com.toedter.calendar.JDateChooser();
        txtAddress = new javax.swing.JTextField();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        pwPass = new javax.swing.JPasswordField();
        pwConfirm = new javax.swing.JPasswordField();
        btnReset = new javax.swing.JButton();
        lvMinimize = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(221, 229, 232));
        jPanel3.setForeground(new java.awt.Color(134, 1, 4));
        jPanel3.setPreferredSize(new java.awt.Dimension(678, 600));

        radBtnManager.setBackground(new java.awt.Color(221, 229, 232));
        btnGroupType.add(radBtnManager);
        radBtnManager.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        radBtnManager.setForeground(new java.awt.Color(134, 1, 4));
        radBtnManager.setText("Quản lý");
        radBtnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnManagerActionPerformed(evt);
            }
        });

        cbExpertise.setBackground(new java.awt.Color(221, 229, 232));
        cbExpertise.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        cbExpertise.setForeground(new java.awt.Color(134, 1, 4));
        cbExpertise.setBorder(null);

        txtExperience.setBackground(new java.awt.Color(221, 229, 232));
        txtExperience.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        txtExperience.setForeground(new java.awt.Color(134, 1, 4));
        txtExperience.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExperience.setText("EXPERIENCE");
        txtExperience.setBorder(null);
        txtExperience.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtExperienceFocusGained(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator14.setForeground(new java.awt.Color(134, 1, 4));

        jLabel12.setBackground(new java.awt.Color(221, 229, 232));
        jLabel12.setFont(new java.awt.Font("#9Slide03 IcielSmoothy Sans", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(134, 1, 4));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SỐ NĂM KINH NGHIỆM");

        jSeparator15.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator15.setForeground(new java.awt.Color(221, 229, 232));

        jLabel14.setBackground(new java.awt.Color(221, 229, 232));
        jLabel14.setFont(new java.awt.Font("#9Slide03 IcielSmoothy Sans", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(134, 1, 4));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CHUYÊN MÔN");

        jSeparator17.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator17.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator16.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator16.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator19.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator19.setForeground(new java.awt.Color(134, 1, 4));

        jLabel11.setBackground(new java.awt.Color(221, 229, 232));
        jLabel11.setFont(new java.awt.Font("#9Slide03 IcielSmoothy Sans", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(134, 1, 4));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VỊ TRÍ");

        radBtnInstructor.setBackground(new java.awt.Color(221, 229, 232));
        btnGroupType.add(radBtnInstructor);
        radBtnInstructor.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        radBtnInstructor.setForeground(new java.awt.Color(134, 1, 4));
        radBtnInstructor.setText("Huấn luyện viên");
        radBtnInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnInstructorActionPerformed(evt);
            }
        });

        radBtnCashier.setBackground(new java.awt.Color(221, 229, 232));
        btnGroupType.add(radBtnCashier);
        radBtnCashier.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        radBtnCashier.setForeground(new java.awt.Color(134, 1, 4));
        radBtnCashier.setText("Thu ngân");
        radBtnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnCashierActionPerformed(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator13.setForeground(new java.awt.Color(134, 1, 4));

        txtSalary.setBackground(new java.awt.Color(221, 229, 232));
        txtSalary.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(134, 1, 4));
        txtSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalary.setText("SALARY");
        txtSalary.setBorder(null);

        jLabel10.setBackground(new java.awt.Color(221, 229, 232));
        jLabel10.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(134, 1, 4));
        jLabel10.setText("VNĐ");

        jSeparator20.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator20.setForeground(new java.awt.Color(221, 229, 232));

        jSeparator1.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator1.setForeground(new java.awt.Color(221, 229, 232));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setBackground(new java.awt.Color(221, 229, 232));
        jLabel13.setFont(new java.awt.Font("#9Slide03 IcielSmoothy Sans", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(134, 1, 4));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LƯƠNG");

        jSeparator21.setBackground(new java.awt.Color(221, 229, 232));
        jSeparator21.setForeground(new java.awt.Color(134, 1, 4));

        jLabel21.setFont(new java.awt.Font("#9Slide03 Montserrat Bold", 0, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(134, 1, 4));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TUYỂN DỤNG");

        lbTime.setFont(new java.awt.Font("#9Slide03 HelvetIns", 0, 14)); // NOI18N
        lbTime.setForeground(new java.awt.Color(134, 1, 4));
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTime.setText("Ngày");

        lbClock.setFont(new java.awt.Font("#9Slide03 HelvetIns", 0, 14)); // NOI18N
        lbClock.setForeground(new java.awt.Color(134, 1, 4));
        lbClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClock.setText("giờ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radBtnInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radBtnCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radBtnManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator14)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cbExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator16)
                                .addContainerGap())))
                    .addComponent(jSeparator20)
                    .addComponent(jSeparator15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator17)
                            .addComponent(jSeparator19)
                            .addComponent(txtExperience, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtSalary)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator21)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTime)
                            .addComponent(lbClock))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbExpertise)
                            .addComponent(radBtnInstructor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radBtnCashier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radBtnManager, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtExperience, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtSalary)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbClock, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbTime)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(134, 1, 4));
        jPanel1.setForeground(new java.awt.Color(221, 229, 232));

        jLabel5.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(221, 229, 232));
        jLabel5.setText("GIỚI TÍNH");

        jLabel6.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(221, 229, 232));
        jLabel6.setText("NGÀY ĐĂNG KÝ");

        dcBirthday.setBackground(new java.awt.Color(134, 1, 4));
        dcBirthday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dcBirthday.setForeground(new java.awt.Color(221, 229, 232));

        dcDateJoin.setBackground(new java.awt.Color(134, 1, 4));
        dcDateJoin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dcDateJoin.setForeground(new java.awt.Color(221, 229, 232));

        txtAddress.setBackground(new java.awt.Color(134, 1, 4));
        txtAddress.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(221, 229, 232));
        txtAddress.setText("ADDRESS");
        txtAddress.setBorder(null);
        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAddressFocusGained(evt);
            }
        });

        radioBtnMale.setBackground(new java.awt.Color(134, 1, 4));
        btnGroupGender.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radioBtnMale.setForeground(new java.awt.Color(221, 229, 232));
        radioBtnMale.setText("Nam");

        radioBtnFemale.setBackground(new java.awt.Color(134, 1, 4));
        btnGroupGender.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radioBtnFemale.setForeground(new java.awt.Color(221, 229, 232));
        radioBtnFemale.setText("Nữ");

        pwPass.setBackground(new java.awt.Color(134, 1, 4));
        pwPass.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        pwPass.setForeground(new java.awt.Color(221, 229, 232));
        pwPass.setText("password");
        pwPass.setBorder(null);
        pwPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwPassFocusGained(evt);
            }
        });

        pwConfirm.setBackground(new java.awt.Color(134, 1, 4));
        pwConfirm.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        pwConfirm.setForeground(new java.awt.Color(221, 229, 232));
        pwConfirm.setText("password");
        pwConfirm.setBorder(null);
        pwConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwConfirmFocusGained(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(134, 1, 4));
        btnReset.setFont(new java.awt.Font("#9Slide03 Roboto", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(221, 229, 232));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ic_sync_white_24dp.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lvMinimize.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lvMinimize.setForeground(new java.awt.Color(221, 229, 232));
        lvMinimize.setText("-");
        lvMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvMinimizeMouseClicked(evt);
            }
        });

        lbExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbExit.setForeground(new java.awt.Color(221, 229, 232));
        lbExit.setText("X");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 229, 232));
        jLabel2.setText("HỌ TÊN");

        txtName.setBackground(new java.awt.Color(134, 1, 4));
        txtName.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(221, 229, 232));
        txtName.setText("FULL NAME");
        txtName.setBorder(null);
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(221, 229, 232));
        jLabel17.setText("NGÀY SINH");

        jSeparator3.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator3.setForeground(new java.awt.Color(221, 229, 232));

        jSeparator4.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator4.setForeground(new java.awt.Color(221, 229, 232));

        jSeparator5.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator5.setForeground(new java.awt.Color(221, 229, 232));

        jLabel18.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(221, 229, 232));
        jLabel18.setText("SỐ ĐIỆN THOẠI");

        jLabel1.setBackground(new java.awt.Color(134, 1, 4));
        jLabel1.setFont(new java.awt.Font("#9Slide03 Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 229, 232));
        jLabel1.setText("+84");

        txtTelephone.setBackground(new java.awt.Color(134, 1, 4));
        txtTelephone.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtTelephone.setForeground(new java.awt.Color(221, 229, 232));
        txtTelephone.setText("TELEPHONE");
        txtTelephone.setBorder(null);
        txtTelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusGained(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator6.setForeground(new java.awt.Color(221, 229, 232));

        jLabel15.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(221, 229, 232));
        jLabel15.setText("MẬT KHẨU");

        jLabel19.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(221, 229, 232));
        jLabel19.setText("NHẬP LẠI MK");

        jSeparator7.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator7.setForeground(new java.awt.Color(221, 229, 232));

        jLabel20.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(221, 229, 232));
        jLabel20.setText("ĐỊA CHỈ");

        jSeparator8.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator8.setForeground(new java.awt.Color(221, 229, 232));

        jSeparator9.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator9.setForeground(new java.awt.Color(221, 229, 232));

        jSeparator10.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator10.setForeground(new java.awt.Color(221, 229, 232));

        btnSignUp.setBackground(new java.awt.Color(134, 1, 4));
        btnSignUp.setFont(new java.awt.Font("#9Slide03 Roboto", 0, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(221, 229, 232));
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ic_send_white_24dp.png"))); // NOI18N
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(134, 1, 4));
        jLabel4.setFont(new java.awt.Font("#9Slide03 HelvetIns", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Product by SOS-team");

        jLabel16.setBackground(new java.awt.Color(134, 1, 4));
        jLabel16.setFont(new java.awt.Font("#9Slide03 Montserrat Bold", 0, 40)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(221, 229, 232));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("LÝ LỊCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78)
                        .addComponent(lvMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator8)
                            .addComponent(jSeparator5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(dcBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pwPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator6)
                            .addComponent(pwConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator10)
                            .addComponent(jLabel19)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDateJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator9)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioBtnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioBtnFemale)
                                .addGap(43, 43, 43))
                            .addComponent(jSeparator3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbExit))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioBtnFemale)
                        .addComponent(radioBtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcDateJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnManagerActionPerformed
        // TODO add your handling code here:
        if (radBtnManager.isSelected()) {
            cbExpertise.setSelectedIndex(0);
            cbExpertise.setEnabled(false);
        }
    }//GEN-LAST:event_radBtnManagerActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        try {
            // TODO add your handling code here:
            String tenNV = txtName.getText();
            String diaChi = txtAddress.getText();
            String SDT = txtTelephone.getText();
            String tienLuong = txtSalary.getText();
            String matKhau = pwPass.getText();
            String pass = setKey(matKhau + SDT);
            String xacNhan = pwConfirm.getText();
            String confirm = setKey(xacNhan + SDT);
            Date ngSinh = dcBirthday.getDate();
            String sNgSinh = String.format("%1$td/%1$tm/%1$tY", ngSinh);
            Date ngVL = dcDateJoin.getDate();
            String sNgVL = String.format("%1$td/%1$tm/%1$tY", ngVL);
            String gioiTinh = null;
            if (radioBtnMale.isSelected() == true) {
                gioiTinh = radioBtnMale.getText();
            } else if (radioBtnFemale.isSelected() == true) {
                gioiTinh = radioBtnFemale.getText();
            }

            String namKN = txtExperience.getText();
            String chuyenMon = (String) cbExpertise.getSelectedItem();

            String viTri = null;
            if (radBtnInstructor.isSelected() == true) {
                viTri = radBtnInstructor.getText();
            } else if (radBtnCashier.isSelected() == true) {
                viTri = radBtnCashier.getText();
                chuyenMon = null;
            } else if (radBtnManager.isSelected() == true) {
                viTri = radBtnManager.getText();
                chuyenMon = null;
            }

            Staff nhanVien = new Staff();

            if (tenNV.equals("") || SDT.equals("") || matKhau.equals("")
                    || xacNhan.equals("") || diaChi.equals("")
                    || sNgSinh.equals("") || sNgVL.equals("") || gioiTinh.equals("")
                    || namKN.equals("") || viTri.equals("") || tienLuong.equals("")) {
                JOptionPane.showMessageDialog(this, "KHÔNG ĐƯỢC để trống trường nào cả!", "Trống", JOptionPane.ERROR_MESSAGE);
            } else {
                if (pass.equals(confirm)) {
                    if (SDT.length() != 9) {
                        JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng", "Số điện thoại sai", JOptionPane.WARNING_MESSAGE);
                        txtTelephone.setText("");
                        pwConfirm.setText("");
                        pwPass.setText("");
                        return;
                    }
                    if (ngSinh.compareTo(ngVL) >= 0) {
                        JOptionPane.showMessageDialog(this, "Ngày sinh phải nhỏ hơn ngày vào làm", "Lỗi ngày", JOptionPane.ERROR_MESSAGE);
                        dcBirthday.setDate(new Date());
                        dcDateJoin.setDate(new Date());
                        pwConfirm.setText("");
                        pwPass.setText("");
                    } else {
                        int themNV = nhanVien.addStaff(tenNV, sNgSinh, sNgVL, gioiTinh, diaChi, SDT, pass, tienLuong, viTri, namKN, chuyenMon);

                        if (themNV > 0) {
                            JOptionPane.showMessageDialog(this, "Thêm Nhân Viên THÀNH CÔNG!");
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm Nhân Viên THẤT BẠI!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            resetStaffSignUp();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!", "Mật Khẩu Sai", JOptionPane.WARNING_MESSAGE);
                    txtTelephone.setText("");
                    pwConfirm.setText("");
                    pwPass.setText("");
                }
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StaffSignUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtTelephone.setText("");
            pwConfirm.setText("");
            pwPass.setText("");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void radBtnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnCashierActionPerformed
        // TODO add your handling code here:
        if (radBtnCashier.isSelected()) {
            cbExpertise.setSelectedIndex(0);
            cbExpertise.setEnabled(false);
        }
    }//GEN-LAST:event_radBtnCashierActionPerformed

    private void radBtnInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnInstructorActionPerformed
        // TODO add your handling code here:
        if (radBtnInstructor.isSelected()) {
            cbExpertise.setSelectedIndex(0);
            cbExpertise.setEnabled(true);
        }
    }//GEN-LAST:event_radBtnInstructorActionPerformed

    private void txtTelephoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneFocusGained
        // TODO add your handling code here:
        txtTelephone.setText("");
    }//GEN-LAST:event_txtTelephoneFocusGained

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbExitMouseClicked

    private void lvMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvMinimizeMouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lvMinimizeMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here
        resetStaffSignUp();
    }//GEN-LAST:event_btnResetActionPerformed

    private void pwPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwPassFocusGained
        // TODO add your handling code here:
        pwPass.setText("");
    }//GEN-LAST:event_pwPassFocusGained

    private void pwConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwConfirmFocusGained
        // TODO add your handling code here:
        pwConfirm.setText("");
    }//GEN-LAST:event_pwConfirmFocusGained

    private void txtAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusGained
        // TODO add your handling code here:
        txtAddress.setText("");
    }//GEN-LAST:event_txtAddressFocusGained

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        txtName.setText("");
    }//GEN-LAST:event_txtNameFocusGained

    private void txtExperienceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExperienceFocusGained
        // TODO add your handling code here:
        txtExperience.setText("");
    }//GEN-LAST:event_txtExperienceFocusGained

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void resetStaffSignUp() {
        txtName.setText("FULL NAME");
        txtAddress.setText("ADDRESS");
        txtTelephone.setText("TELEPHONE");
        pwPass.setText("PASSWORD");
        pwConfirm.setText("CONFIRM");
        txtSalary.setText("");
        dcBirthday.setDate(new Date());
        dcDateJoin.setDate(new Date());
        cbExpertise.setSelectedIndex(0);
        cbExpertise.setEnabled(false);
        txtExperience.setText("");
        btnGroupGender.clearSelection();
        btnGroupType.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffSignUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StaffSignUp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cbExpertise;
    private com.toedter.calendar.JDateChooser dcBirthday;
    private com.toedter.calendar.JDateChooser dcDateJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbClock;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lvMinimize;
    private javax.swing.JPasswordField pwConfirm;
    private javax.swing.JPasswordField pwPass;
    private javax.swing.JRadioButton radBtnCashier;
    private javax.swing.JRadioButton radBtnInstructor;
    private javax.swing.JRadioButton radBtnManager;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
