/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Processes.ClockThread;
import Processes.ReportView;
import Processes.Staff;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Hindu
 */
public class StaffForm extends javax.swing.JFrame {

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
        setResizable(false);
        initClock();
        this.setLocationRelativeTo(null);
        showCbStaffData();
        resetStaff();
    }

    private void initClock() {
        ClockThread ct = new ClockThread(lbClock, lbTime);
        ct.start();
    }

    DefaultTableModel tbModelStaff = null;
    public static String MaNV = "";

    private void showCbStaffData() {
        ArrayList<String> data = Staff.getData();
        for (String dt : data) {
            cbExpertise.addItem(dt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        btnGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        dcBirthday = new com.toedter.calendar.JDateChooser();
        dcDateJoin = new com.toedter.calendar.JDateChooser();
        txtAddress = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        radBtnInstructor = new javax.swing.JRadioButton();
        radBtnCashier = new javax.swing.JRadioButton();
        radBtnManager = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        cbExpertise = new javax.swing.JComboBox<>();
        txtExperience = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();
        btnSignUpStaff = new javax.swing.JButton();
        lvMinimize = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbClock = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(134, 1, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(498, 664));

        txtName.setBackground(new java.awt.Color(221, 229, 232));
        txtName.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(134, 1, 4));
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        dcBirthday.setBackground(new java.awt.Color(221, 229, 232));
        dcBirthday.setForeground(new java.awt.Color(134, 1, 4));
        dcBirthday.setDateFormatString("dd/MM/yyyy");

        dcDateJoin.setBackground(new java.awt.Color(221, 229, 232));
        dcDateJoin.setForeground(new java.awt.Color(134, 1, 4));
        dcDateJoin.setDateFormatString("dd/MM/yyyy");

        txtAddress.setBackground(new java.awt.Color(221, 229, 232));
        txtAddress.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(134, 1, 4));
        txtAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelephone.setBackground(new java.awt.Color(221, 229, 232));
        txtTelephone.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtTelephone.setForeground(new java.awt.Color(134, 1, 4));
        txtTelephone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSalary.setBackground(new java.awt.Color(221, 229, 232));
        txtSalary.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(134, 1, 4));
        txtSalary.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        radioBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(radioBtnMale);
        radioBtnMale.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radioBtnMale.setForeground(new java.awt.Color(134, 1, 4));
        radioBtnMale.setText("Nam");

        radioBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(radioBtnFemale);
        radioBtnFemale.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radioBtnFemale.setForeground(new java.awt.Color(134, 1, 4));
        radioBtnFemale.setText("Nữ");

        jLabel10.setBackground(new java.awt.Color(221, 229, 232));
        jLabel10.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(134, 1, 4));
        jLabel10.setText("VNĐ");

        btnReset.setBackground(new java.awt.Color(221, 229, 232));
        btnReset.setFont(new java.awt.Font("#9Slide03 Neutra", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(134, 1, 4));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-refresh-30.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        radBtnInstructor.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupType.add(radBtnInstructor);
        radBtnInstructor.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radBtnInstructor.setForeground(new java.awt.Color(134, 1, 4));
        radBtnInstructor.setText("Huấn luyện viên");

        radBtnCashier.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupType.add(radBtnCashier);
        radBtnCashier.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radBtnCashier.setForeground(new java.awt.Color(134, 1, 4));
        radBtnCashier.setText("Thu ngân");

        radBtnManager.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupType.add(radBtnManager);
        radBtnManager.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        radBtnManager.setForeground(new java.awt.Color(134, 1, 4));
        radBtnManager.setText("Quản lý");

        jLabel15.setBackground(new java.awt.Color(221, 229, 232));
        jLabel15.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(134, 1, 4));
        jLabel15.setText("+84");

        cbExpertise.setBackground(new java.awt.Color(221, 229, 232));
        cbExpertise.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        cbExpertise.setForeground(new java.awt.Color(134, 1, 4));
        cbExpertise.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtExperience.setBackground(new java.awt.Color(221, 229, 232));
        txtExperience.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        txtExperience.setForeground(new java.awt.Color(134, 1, 4));
        txtExperience.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDelete.setBackground(new java.awt.Color(221, 229, 232));
        btnDelete.setFont(new java.awt.Font("#9Slide03 Neutra", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(134, 1, 4));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-delete-32.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(221, 229, 232));
        btnUpdate.setFont(new java.awt.Font("#9Slide03 Neutra", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(134, 1, 4));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-edit-30.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("#9Slide03 Montserrat Bold", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(134, 1, 4));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("THÔNG TIN NHÂN VIÊN");

        jLabel2.setBackground(new java.awt.Color(221, 229, 232));
        jLabel2.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(134, 1, 4));
        jLabel2.setText("Họ tên");

        jLabel14.setBackground(new java.awt.Color(221, 229, 232));
        jLabel14.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(134, 1, 4));
        jLabel14.setText("Ngày sinh");

        jLabel16.setBackground(new java.awt.Color(221, 229, 232));
        jLabel16.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(134, 1, 4));
        jLabel16.setText("Giới tính");

        jLabel18.setBackground(new java.awt.Color(221, 229, 232));
        jLabel18.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(134, 1, 4));
        jLabel18.setText("Ngày đăng ký");

        jLabel19.setBackground(new java.awt.Color(221, 229, 232));
        jLabel19.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(134, 1, 4));
        jLabel19.setText("Địa chỉ");

        jLabel20.setBackground(new java.awt.Color(221, 229, 232));
        jLabel20.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(134, 1, 4));
        jLabel20.setText("Số điện thoại");

        jLabel24.setBackground(new java.awt.Color(221, 229, 232));
        jLabel24.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(134, 1, 4));
        jLabel24.setText("Lương");

        jLabel22.setBackground(new java.awt.Color(221, 229, 232));
        jLabel22.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(134, 1, 4));
        jLabel22.setText("Chuyên môn");

        jLabel23.setBackground(new java.awt.Color(221, 229, 232));
        jLabel23.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(134, 1, 4));
        jLabel23.setText("Số năm kinh nghiệm");

        jLabel25.setBackground(new java.awt.Color(221, 229, 232));
        jLabel25.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(134, 1, 4));
        jLabel25.setText("Vị trí");

        jSeparator1.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator1.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator2.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator2.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator3.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator3.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator4.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator4.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator5.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator5.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator6.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator6.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator7.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator7.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator8.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator8.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator9.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator9.setForeground(new java.awt.Color(134, 1, 4));

        jSeparator10.setBackground(new java.awt.Color(134, 1, 4));
        jSeparator10.setForeground(new java.awt.Color(134, 1, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(radBtnInstructor)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(dcDateJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(dcBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel22)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTelephone))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel23)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel24)
                                            .addGap(55, 55, 55)
                                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(radioBtnMale)
                                            .addGap(80, 80, 80)
                                            .addComponent(radioBtnFemale)
                                            .addGap(37, 37, 37))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnDelete)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnUpdate))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(radBtnCashier)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                                            .addComponent(radBtnManager)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnReset)))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDateJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBtnMale)
                    .addComponent(radioBtnFemale))
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExpertise, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radBtnInstructor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnCashier)
                    .addComponent(radBtnManager))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReset)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(134, 1, 4));
        jPanel2.setForeground(new java.awt.Color(221, 229, 232));

        txtSearch.setBackground(new java.awt.Color(134, 1, 4));
        txtSearch.setFont(new java.awt.Font("#9Slide03 Roboto Condensed Bold", 0, 36)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setText("SEARCH");
        txtSearch.setBorder(null);
        txtSearch.setPreferredSize(new java.awt.Dimension(139, 29));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        tbStaff.setBackground(new java.awt.Color(134, 1, 4));
        tbStaff.setFont(new java.awt.Font("#9Slide03 Roboto Condensed", 0, 12)); // NOI18N
        tbStaff.setForeground(new java.awt.Color(221, 229, 232));
        tbStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "Giới tính", "Ngày vào làm", "Địa chỉ", "SĐT", "Chuyên môn", "Số năm kinh nghiệm", "Vị trí", "Lương"
            }
        ));
        tbStaff.setGridColor(new java.awt.Color(0, 0, 0));
        tbStaff.setShowGrid(true);
        tbStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStaff);

        btnSignUpStaff.setBackground(new java.awt.Color(134, 1, 4));
        btnSignUpStaff.setFont(new java.awt.Font("#9Slide03 Montserrat Black", 0, 24)); // NOI18N
        btnSignUpStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ic_fiber_new_white_36dp.png"))); // NOI18N
        btnSignUpStaff.setText("TUYỂN DỤNG");
        btnSignUpStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpStaffActionPerformed(evt);
            }
        });

        lvMinimize.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lvMinimize.setForeground(new java.awt.Color(221, 229, 232));
        lvMinimize.setText("-");
        lvMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvMinimizeMouseClicked(evt);
            }
        });

        lbExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbExit.setForeground(new java.awt.Color(221, 229, 232));
        lbExit.setText("X");
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(134, 1, 4));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ic_search_white_18dp.png"))); // NOI18N

        lbClock.setBackground(new java.awt.Color(134, 1, 4));
        lbClock.setFont(new java.awt.Font("#9Slide03 HelvetIns", 0, 14)); // NOI18N
        lbClock.setForeground(new java.awt.Color(255, 255, 255));
        lbClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClock.setText("giờ");

        lbTime.setBackground(new java.awt.Color(134, 1, 4));
        lbTime.setFont(new java.awt.Font("#9Slide03 HelvetIns", 0, 14)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 255, 255));
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTime.setText("Ngày");

        btnPrint.setBackground(new java.awt.Color(255, 255, 255));
        btnPrint.setFont(new java.awt.Font("#9Slide03 Montserrat Black", 0, 24)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(134, 1, 4));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8-name-tag-80.png"))); // NOI18N
        btnPrint.setText("LÀM THẺ NHÂN VIÊN");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTime)
                            .addComponent(lbClock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249)
                        .addComponent(lvMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSignUpStaff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                                .addComponent(btnPrint))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lvMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExit)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbClock, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTime))
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUpStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getRowStaff(int index) {
        try {
            index = tbStaff.getSelectedRow();
            MaNV = (String) tbStaff.getValueAt(index, 0);
            txtName.setText((String) tbStaff.getValueAt(index, 1));
            Date ngS = new SimpleDateFormat("dd/mm/yyyy").parse((String) tbStaff.getValueAt(index, 2));
            dcBirthday.setDate(ngS);

            String gioiTinh = (String) tbStaff.getValueAt(index, 3);
            if (gioiTinh.equals("Nam")) {
                radioBtnMale.setSelected(true);
            } else {
                radioBtnFemale.setSelected(true);
            }
            Date ngVL = new SimpleDateFormat("dd/mm/yyyy").parse((String) tbStaff.getValueAt(index, 4));
            dcDateJoin.setDate(ngVL);
            txtAddress.setText((String) tbStaff.getValueAt(index, 5));
            txtTelephone.setText((String) tbStaff.getValueAt(index, 6));
            txtExperience.setText((String) tbStaff.getValueAt(index, 8));

            String viTri = (String) tbStaff.getValueAt(index, 9);
            switch (viTri) {
                case "Thu ngân" -> {
                    radBtnCashier.setEnabled(true);
                    radBtnCashier.setSelected(true);
                    radBtnInstructor.setEnabled(false);
                    radBtnManager.setEnabled(false);
                    cbExpertise.setSelectedItem(null);
                    cbExpertise.setEnabled(false);
                }
                case "Quản lý" -> {
                    radBtnManager.setEnabled(true);
                    radBtnManager.setSelected(true);
                    radBtnInstructor.setEnabled(false);
                    radBtnCashier.setEnabled(false);
                    cbExpertise.setSelectedItem(null);
                    cbExpertise.setEnabled(false);
                }
                case "Huấn luyện viên" -> {
                    radBtnInstructor.setEnabled(true);
                    radBtnInstructor.setSelected(true);
                    radBtnCashier.setEnabled(false);
                    radBtnManager.setEnabled(false);
                    cbExpertise.setEnabled(true);
                    cbExpertise.setSelectedItem(tbStaff.getValueAt(index, 7));
                }
                default ->
                    throw new AssertionError();
            }
            txtSalary.setText((String) tbStaff.getValueAt(index, 10));
        } catch (ParseException ex) {
            Logger.getLogger(StaffForm.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }

    private void setTableStaff() {
        try {
            Staff nv = new Staff();
            ResultSet rs = nv.insertTableStaff();
            tbModelStaff = (DefaultTableModel) tbStaff.getModel();
            tbModelStaff.setRowCount(0);
            while (rs.next()) {
                String maNV = rs.getString("staff_id");
                String tenNV = rs.getString("staff_name");
                Date ngS = rs.getDate("staff_birthday");
                String sNgS = String.format("%1$td/%1$tm/%1$tY", ngS);
                String gioiTinh = rs.getString("staff_gender");
                Date ngVL = rs.getDate("staff_datejoin");
                String sNgVL = String.format("%1$td/%1$tm/%1$tY", ngVL);
                String diaChi = rs.getString("staff_address");
                String SDT = rs.getString("staff_telephone");
                String chuyenMon = rs.getString("staff_expertise");
                String namKN = rs.getString("staff_experience");
                String viTri = rs.getString("staff_type");
                String luong = rs.getString("staff_salary");
                tbModelStaff.addRow(new Object[]{
                    maNV, tenNV, sNgS, gioiTinh, sNgVL, diaChi, SDT, chuyenMon, namKN, viTri, luong
                });
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StaffForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void resetStaff() {
        tbStaff.setDefaultEditor(Object.class, null);
        txtName.setText("");
        txtAddress.setText("");
        txtTelephone.setText("");
        txtSalary.setText("");
        txtExperience.setText("");
        txtSearch.setText("SEARCH");
        cbExpertise.setSelectedItem(null);
        cbExpertise.setEnabled(false);
        dcBirthday.setDate(new Date());
        dcDateJoin.setDate(new Date());
        btnGroupGender.clearSelection();
        btnGroupType.clearSelection();
        radBtnManager.setEnabled(false);
        radBtnCashier.setEnabled(false);
        radBtnInstructor.setEnabled(false);
        setTableStaff();
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetStaff();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // TODO add your handling code here:
            String SDT = txtTelephone.getText();

            Object[] options = {"Có", "Không", "Hủy"};

            Staff nhanVien = new Staff();

            int result = JOptionPane.showOptionDialog(rootPane,
                    "Bạn có chắc muốn xóa nhân viên +84" + SDT + " hay không?",
                    "Xóa khách hàng", JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

            if (result == JOptionPane.YES_OPTION) {
                int demXoaNV = nhanVien.deleteStaff(SDT);
                if (demXoaNV > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa Nhân Viên THÀNH CÔNG!");
                    resetStaff();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa Nhân Viên THẤT BẠI!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    resetStaff();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hủy thao tác xóa nhân viên");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StaffForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // TODO add your handling code here:
            String tenNV = txtName.getText();
            String diaChi = txtAddress.getText();
            String SDT = txtTelephone.getText();
            String tienLuong = txtSalary.getText();
            Date birthday = dcBirthday.getDate();
            String sBirthday = String.format("%1$td/%1$tm/%1$tY", birthday);
            Date datejoined = dcDateJoin.getDate();
            String sDateJoined = String.format("%1$td/%1$tm/%1$tY", datejoined);
            String gioiTinh = null;
            if (radioBtnMale.isSelected() == true) {
                gioiTinh = radioBtnMale.getText();
            } else if (radioBtnFemale.isSelected() == true) {
                gioiTinh = radioBtnFemale.getText();
            }
            String viTri = null;
            if (radBtnInstructor.isSelected() == true) {
                viTri = radBtnInstructor.getText();
            } else if (radBtnCashier.isSelected() == true) {
                viTri = radBtnCashier.getText();
                cbExpertise.setEditable(false);
            } else if (radBtnManager.isSelected() == true) {
                viTri = radBtnManager.getText();
                cbExpertise.setEditable(false);
            }
            String chuyenMon = (String) cbExpertise.getSelectedItem();
            String namKN = txtExperience.getText();

            Staff nhanVien = new Staff();

            int capnhatNV = nhanVien.updateStaff(tenNV, sBirthday, sDateJoined,
                    gioiTinh, diaChi, SDT, tienLuong, viTri, chuyenMon, namKN);

            if (capnhatNV > 0) {
                JOptionPane.showMessageDialog(this, "Cập nhật Nhân Viên THÀNH CÔNG!");
                resetStaff();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật Nhân Viên THẤT BẠI!",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                resetStaff();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StaffForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        DefaultTableModel SearchTable = (DefaultTableModel) tbStaff.getModel();
        String timkiemNV = txtSearch.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(SearchTable);
        tbStaff.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(timkiemNV));
    }//GEN-LAST:event_txtSearchKeyPressed

    private void btnSignUpStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpStaffActionPerformed
        // TODO add your handling code here:
        StaffSignUp.main(null);
        this.dispose();
    }//GEN-LAST:event_btnSignUpStaffActionPerformed

    private void tbStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStaffMouseClicked
        // TODO add your handling code here:
        getRowStaff(tbStaff.getSelectedRow());
    }//GEN-LAST:event_tbStaffMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void lvMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvMinimizeMouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lvMinimizeMouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbExitMouseClicked

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchFocusGained

    private void XuatTheNV(String s) throws SQLException, ClassNotFoundException, JRException {
        HashMap hs = new HashMap();
        hs.put("STAFF_ID", s);
        String localDir = System.getProperty("user.dir");

        ReportView reportView = new ReportView(localDir + "/src/Report/report9.jrxml", hs);
        reportView.setVisible(false);
    }

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            // TODO add your handling code here:
            if (!MaNV.equals("")) {
                XuatTheNV(MaNV);
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn Nhân Viên cần làm thẻ!", "Làm thẻ nhân viên", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException | JRException ex) {
            Logger.getLogger(StaffForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StaffForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSignUpStaff;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbExpertise;
    private com.toedter.calendar.JDateChooser dcBirthday;
    private com.toedter.calendar.JDateChooser dcDateJoin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbClock;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lvMinimize;
    private javax.swing.JRadioButton radBtnCashier;
    private javax.swing.JRadioButton radBtnInstructor;
    private javax.swing.JRadioButton radBtnManager;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTable tbStaff;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
